In [34]:
import numpy as np

In [35]:
#dim1 
np_array = np.array([1,2,3,4])

In [36]:
#dim2
np_2_array = np.array([[1,2,3,4], [3,4,5,5]])

In [37]:
np_2_array.shape


(2, 4)

In [38]:
np_3_array = np.array([
    [[1,2,3],[4,5,6]],
    [[6,7,8],[6,8,10]]
])

np_3_array.shape

(2, 2, 3)

zeros() - ones() - full()
- Tạo ra mảng có các giá trị bằng nhau

    - zeros() tạo ra mảng các giá trị đều bằng 0
        - Đầu vào là shape của array dưới dạng tuple

    - ones() tạo ra mảng các giá trị đều bằng 1
        - Đầu vào là shape của array dưới dạng tuple

    - full() tạo ra mảng các giá trị bằng nhau và bằng một số cho trước
        - Đầu vào là shape của array dưới dạng tuple và giá trị cho trước

In [39]:
np_1d_zeros = np.zeros((3,))
np_1d_zeros

array([0., 0., 0.])

In [40]:
np_1d_ones = np.ones((3,))
np_1d_ones

array([1., 1., 1.])

In [41]:
np_1d_full = np.full((4,), 9)
np_1d_full

array([9, 9, 9, 9])

Mảng 2 chiều

In [42]:
np_2d_zeros = np.ones((3,2))
np_2d_zeros

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
np_2d_ones = np.zeros((3,2))
np_2d_ones.shape

(3, 2)

In [44]:
np_2d_full = np.full((4,3), 9)
np_2d_full

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [45]:
np_3d_full = np.full((4,2,3), 9)
np_3d_full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [46]:
# ma trận đơn vị
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
#tạo 1 array chạy từ 0 -> 9
number_arr = np.arange(9)
number_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
#tạo 1 mảng từ 3 tới 8
my_arr = np.arange(3,9)
my_arr

array([3, 4, 5, 6, 7, 8])

In [49]:
#tạo 1 mảng giới hạn từ 0 tới 20, bước nhảy 3 đơn vị
my_arr_20 = np.arange(0,20,3)
my_arr_20

array([ 0,  3,  6,  9, 12, 15, 18])

In [50]:
#tạo ma trận ramdom
np.random.random((10,5))

array([[0.17457515, 0.0998538 , 0.59567454, 0.25445274, 0.02225095],
       [0.19130618, 0.45654817, 0.42520009, 0.0974574 , 0.41026868],
       [0.79750255, 0.35156366, 0.72565422, 0.01015461, 0.1408092 ],
       [0.29421362, 0.60090156, 0.28072604, 0.7089336 , 0.82544854],
       [0.64431748, 0.59237488, 0.34273329, 0.43154769, 0.84986178],
       [0.3256897 , 0.12574656, 0.57339622, 0.26658253, 0.54375045],
       [0.20612987, 0.24113204, 0.48987034, 0.3627576 , 0.47408906],
       [0.51791773, 0.64626897, 0.87368599, 0.15659201, 0.75806219],
       [0.64635459, 0.20800725, 0.26473535, 0.72053313, 0.27904336],
       [0.80314149, 0.14075384, 0.83428624, 0.31874778, 0.23570662]])