In [2]:
import numpy as np

In [4]:
number_2D = np.array([[4,5,6], [7, 8, 9]])
number_2D

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
#truy cập hàng
number_2D[0]

#truy cập hàng cuối của ma trận
number_2D[-1]

array([7, 8, 9])

In [8]:
#truy cập cột
number_2D[:,0]

# truy cập cột cuối cùng của ma trận
number_2D[:,-1]

array([6, 9])

In [9]:
awesome = np.array([
    [1, 2, 3, 4, 5, 6, 7],
    [8, 9, 4, 5, 8, 9, 0],
    [2, 9, 7, 8, 0, 4, 5],
    [9, 6, 4, 9, 3, 7, 2],
])

In [10]:
# truy cập hàng 1 cột 2
awesome[0,1]

2

In [11]:
# truy cập hàng 2 cột 3
awesome[1,2]

4