In [1]:
import numpy as np

In [2]:
numbers_1d = np.arange(10)

In [5]:
for item in np.nditer(numbers_1d):
    print(item)

0
1
2
3
4
5
6
7
8
9


In [6]:
# Mảng 2chieeuf
np_2d_arr = np.random.random((3,4))
np_2d_arr

array([[0.74270792, 0.13146358, 0.78093516, 0.08390543],
       [0.1674842 , 0.18615167, 0.86917712, 0.52134186],
       [0.89787399, 0.01591842, 0.98342641, 0.36723886]])

In [7]:
for item in np.nditer(np_2d_arr):
    print(item)

0.7427079234694552
0.13146358396140212
0.780935164168968
0.08390542579264137
0.16748420163054845
0.18615167008404776
0.86917711606154
0.5213418555734572
0.8978739854429001
0.015918416679148617
0.983426411410027
0.36723886365378144


In [9]:
#mảng 3 chiều
numbers_3d_arr = np.random.random((2,3,4))

for item in np.nditer(numbers_3d_arr):
    print(item)

0.31592094270464854
0.8069121730346975
0.4739679928778877
0.8671525963044704
0.9924348967685692
0.25881687019207145
0.3255607175241392
0.05742340932364931
0.08054038869636682
0.9730893672945047
0.7438024989944229
0.13810265912533348
0.32987212294852086
0.23780221229478038
0.8625256256836268
0.05769636876912443
0.9491007788469042
0.9003984895543706
0.5928942936190582
0.21015777369402378
0.41881757000551545
0.3754817366206812
0.8752018479918061
0.886638126694479


In [13]:
#Thay đổi giá trị trong quá trình lặp
numbers = np.arange(7)
numbers

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
# Bình phương mỗi phần tử
# Chú ý: Thêm cờ op_flags = ['readwrite'] để bật chế độ có thể thay đổi các phần tử trong mảng

In [14]:
for item in np.nditer(numbers, op_flags=['readwrite']):
    item[...] = item ** 2
numbers

array([ 0,  1,  4,  9, 16, 25, 36])

Lặp qua dòng

In [17]:
float_2D = np.random.random((2, 2))
float_2D

array([[0.80193894, 0.65458358],
       [0.61717001, 0.11940071]])

In [23]:
# flags=['external_loop'] -> làm cho giá trị nhận được là mảng 1 chiều
# order='F' -> thứ tự F nếu các mảng liền kề nhau
# Controls the iteration order. ‘C’ means C order, ‘F’ means Fortran order, ‘A’ means ‘F’ order if all the arrays are Fortran contiguous, ‘C’ order otherwise, and ‘K’ means as close to the order the array elements appear in memory as possible. This also affects the element memory order of allocate operands, as they are allocated to be compatible with iteration order. Default is ‘K’.
for item in np.nditer(float_2D, flags=['external_loop'], order='C'):
    print(item)

[0.80193894 0.65458358 0.61717001 0.11940071]
